export default [
    {
      "login": "davidhs",
      "id": 1169839,
      "node_id": "MDQ6VXNlcjExNjk4Mzk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1169839?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/davidhs",
      "html_url": "https://github.com/davidhs",
      "followers_url": "https://api.github.com/users/davidhs/followers",
      "following_url": "https://api.github.com/users/davidhs/following{/other_user}",
      "gists_url": "https://api.github.com/users/davidhs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/davidhs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/davidhs/subscriptions",
      "organizations_url": "https://api.github.com/users/davidhs/orgs",
      "repos_url": "https://api.github.com/users/davidhs/repos",
      "events_url": "https://api.github.com/users/davidhs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/davidhs/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "Fridrikhr",
      "id": 42745573,
      "node_id": "MDQ6VXNlcjQyNzQ1NTcz",
      "avatar_url": "https://avatars.githubusercontent.com/u/42745573?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Fridrikhr",
      "html_url": "https://github.com/Fridrikhr",
      "followers_url": "https://api.github.com/users/Fridrikhr/followers",
      "following_url": "https://api.github.com/users/Fridrikhr/following{/other_user}",
      "gists_url": "https://api.github.com/users/Fridrikhr/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Fridrikhr/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Fridrikhr/subscriptions",
      "organizations_url": "https://api.github.com/users/Fridrikhr/orgs",
      "repos_url": "https://api.github.com/users/Fridrikhr/repos",
      "events_url": "https://api.github.com/users/Fridrikhr/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Fridrikhr/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "bjorgvinhall",
      "id": 43784017,
      "node_id": "MDQ6VXNlcjQzNzg0MDE3",
      "avatar_url": "https://avatars.githubusercontent.com/u/43784017?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bjorgvinhall",
      "html_url": "https://github.com/bjorgvinhall",
      "followers_url": "https://api.github.com/users/bjorgvinhall/followers",
      "following_url": "https://api.github.com/users/bjorgvinhall/following{/other_user}",
      "gists_url": "https://api.github.com/users/bjorgvinhall/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bjorgvinhall/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bjorgvinhall/subscriptions",
      "organizations_url": "https://api.github.com/users/bjorgvinhall/orgs",
      "repos_url": "https://api.github.com/users/bjorgvinhall/repos",
      "events_url": "https://api.github.com/users/bjorgvinhall/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bjorgvinhall/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "Schuleboogie",
      "id": 15818193,
      "node_id": "MDQ6VXNlcjE1ODE4MTkz",
      "avatar_url": "https://avatars.githubusercontent.com/u/15818193?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Schuleboogie",
      "html_url": "https://github.com/Schuleboogie",
      "followers_url": "https://api.github.com/users/Schuleboogie/followers",
      "following_url": "https://api.github.com/users/Schuleboogie/following{/other_user}",
      "gists_url": "https://api.github.com/users/Schuleboogie/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Schuleboogie/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Schuleboogie/subscriptions",
      "organizations_url": "https://api.github.com/users/Schuleboogie/orgs",
      "repos_url": "https://api.github.com/users/Schuleboogie/repos",
      "events_url": "https://api.github.com/users/Schuleboogie/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Schuleboogie/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "PallFreyr",
      "id": 72401713,
      "node_id": "MDQ6VXNlcjcyNDAxNzEz",
      "avatar_url": "https://avatars.githubusercontent.com/u/72401713?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/PallFreyr",
      "html_url": "https://github.com/PallFreyr",
      "followers_url": "https://api.github.com/users/PallFreyr/followers",
      "following_url": "https://api.github.com/users/PallFreyr/following{/other_user}",
      "gists_url": "https://api.github.com/users/PallFreyr/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/PallFreyr/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/PallFreyr/subscriptions",
      "organizations_url": "https://api.github.com/users/PallFreyr/orgs",
      "repos_url": "https://api.github.com/users/PallFreyr/repos",
      "events_url": "https://api.github.com/users/PallFreyr/events{/privacy}",
      "received_events_url": "https://api.github.com/users/PallFreyr/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "Almar10",
      "id": 42998645,
      "node_id": "MDQ6VXNlcjQyOTk4NjQ1",
      "avatar_url": "https://avatars.githubusercontent.com/u/42998645?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Almar10",
      "html_url": "https://github.com/Almar10",
      "followers_url": "https://api.github.com/users/Almar10/followers",
      "following_url": "https://api.github.com/users/Almar10/following{/other_user}",
      "gists_url": "https://api.github.com/users/Almar10/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Almar10/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Almar10/subscriptions",
      "organizations_url": "https://api.github.com/users/Almar10/orgs",
      "repos_url": "https://api.github.com/users/Almar10/repos",
      "events_url": "https://api.github.com/users/Almar10/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Almar10/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "valtyr",
      "id": 3050355,
      "node_id": "MDQ6VXNlcjMwNTAzNTU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3050355?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/valtyr",
      "html_url": "https://github.com/valtyr",
      "followers_url": "https://api.github.com/users/valtyr/followers",
      "following_url": "https://api.github.com/users/valtyr/following{/other_user}",
      "gists_url": "https://api.github.com/users/valtyr/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/valtyr/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/valtyr/subscriptions",
      "organizations_url": "https://api.github.com/users/valtyr/orgs",
      "repos_url": "https://api.github.com/users/valtyr/repos",
      "events_url": "https://api.github.com/users/valtyr/events{/privacy}",
      "received_events_url": "https://api.github.com/users/valtyr/received_events",
      "type": "User",
      "site_admin": false
    }
  ]