export default {
    "login": "KristinnGodfrey",
    "id": 20058306,
    "node_id": "MDQ6VXNlcjIwMDU4MzA2",
    "avatar_url": "https://avatars.githubusercontent.com/u/20058306?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/KristinnGodfrey",
    "html_url": "https://github.com/KristinnGodfrey",
    "followers_url": "https://api.github.com/users/KristinnGodfrey/followers",
    "following_url": "https://api.github.com/users/KristinnGodfrey/following{/other_user}",
    "gists_url": "https://api.github.com/users/KristinnGodfrey/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/KristinnGodfrey/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/urs/KristinnGodfrey/subscriptions",
    "organizations_url": "https://api.github.com/users/KristinnGodfrey/orgs",
    "repos_url": "https://api.github.com/users/KristinnGodfrey/repos",
    "events_url": "https://api.github.com/users/KristinnGodfrey/events{/privacy}",
    "received_events_url": "https://api.github.com/users/KristinnGodfrey/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Kristinn Godfrey",
    "company": null,
    "blog": "kristinngodfrey.herokuapp.com",
    "location": "Reykjavík, Iceland",
    "email": null,
    "hireable": true,
    "bio": null,
    "twitter_username": "kristinngodfrey",
    "public_repos": 43,
    "public_gists": 0,
    "followers": 7,
    "following": 42,
    "created_at": "2016-06-21T03:46:42Z",
    "updated_at": "2021-02-11T18:24:04Z"
  };